### ISSUE TITLE
Scroll position reverts to top of page when data added

### ISSUE THREAD

**Issue by andregoldstein** [abecks/meteor-infinite-scroll#11]
Hi there when more data is loaded in the scroll position goes straight to the top of the page, is this intended behaviour?

Thanks!

**Comment by abecks** [comment]
That definitely should not be happening. Can you provide an example?

**Comment by abecks** [comment]
Please feel free to re-open with an example

**Comment by maxfi** [comment]
I'm having the same issue. It appears that the problem is that when the limit is incremented the previous subscription is stopped and the docs are removed from minimongo clearing all the docs in the view and therefore decreasing the height of the viewport causing the browser to scroll back up.

Any ideas @abecks? Thanks.
